// <auto-generated />
using System;
using API_AutomaG.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace API_AutomaG.Migrations
{
    [DbContext(typeof(API_AutomaGContext))]
    [Migration("20260217145654_automagest_bdd")]
    partial class automagest_bdd
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Modelos_AutomaG.Aspirantes", b =>
                {
                    b.Property<string>("idasp")
                        .HasColumnType("text")
                        .HasColumnName("idasp");

                    b.Property<string>("apellidoasp")
                        .HasColumnType("text")
                        .HasColumnName("apellidoasp");

                    b.Property<string>("ciudadasp")
                        .HasColumnType("text")
                        .HasColumnName("ciudadasp");

                    b.Property<string>("emailasp")
                        .HasColumnType("text")
                        .HasColumnName("emailasp");

                    b.Property<string>("estadoasp")
                        .HasColumnType("text")
                        .HasColumnName("estadoasp");

                    b.Property<DateTime>("fecharegistro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecharegistro");

                    b.Property<string>("idcon")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("idcon");

                    b.Property<string>("nivelinteres")
                        .HasColumnType("text")
                        .HasColumnName("nivelinteres");

                    b.Property<string>("nombreasp")
                        .HasColumnType("text")
                        .HasColumnName("nombreasp");

                    b.Property<string>("programainteres")
                        .HasColumnType("text")
                        .HasColumnName("programainteres");

                    b.Property<string>("provinciaasp")
                        .HasColumnType("text")
                        .HasColumnName("provinciaasp");

                    b.HasKey("idasp");

                    b.HasIndex("idcon");

                    b.ToTable("aspirantes");
                });

            modelBuilder.Entity("Modelos_AutomaG.CamposConocimiento", b =>
                {
                    b.Property<string>("idcam")
                        .HasColumnType("text")
                        .HasColumnName("idcam");

                    b.Property<string>("codigocam")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("codigocam");

                    b.Property<string>("descripcioncam")
                        .HasColumnType("text")
                        .HasColumnName("descripcioncam");

                    b.Property<string>("estadocam")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estadocam");

                    b.Property<string>("nombrecam")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombrecam");

                    b.HasKey("idcam");

                    b.ToTable("campos_conocimiento");
                });

            modelBuilder.Entity("Modelos_AutomaG.Contactos", b =>
                {
                    b.Property<string>("idcon")
                        .HasColumnType("text")
                        .HasColumnName("idcon");

                    b.Property<DateTime>("fechacontacto")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fechacontacto");

                    b.Property<string>("telefonocon")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("telefonocon");

                    b.HasKey("idcon");

                    b.ToTable("contactos");
                });

            modelBuilder.Entity("Modelos_AutomaG.Horarios", b =>
                {
                    b.Property<string>("idhor")
                        .HasColumnType("text")
                        .HasColumnName("idhor");

                    b.Property<string>("dia")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("dia");

                    b.Property<TimeSpan>("horafin")
                        .HasColumnType("interval")
                        .HasColumnName("horafin");

                    b.Property<TimeSpan>("horainicio")
                        .HasColumnType("interval")
                        .HasColumnName("horainicio");

                    b.Property<string>("idtipo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("idtipo");

                    b.HasKey("idhor");

                    b.HasIndex("idtipo");

                    b.ToTable("horarios");
                });

            modelBuilder.Entity("Modelos_AutomaG.Modalidades", b =>
                {
                    b.Property<string>("idmod")
                        .HasColumnType("text")
                        .HasColumnName("idmod");

                    b.Property<string>("nombremod")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombremod");

                    b.HasKey("idmod");

                    b.ToTable("modalidades");
                });

            modelBuilder.Entity("Modelos_AutomaG.Niveles", b =>
                {
                    b.Property<string>("idniv")
                        .HasColumnType("text")
                        .HasColumnName("idniv");

                    b.Property<string>("codigoniv")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("codigoniv");

                    b.Property<string>("nombreniv")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombreniv");

                    b.HasKey("idniv");

                    b.ToTable("niveles");
                });

            modelBuilder.Entity("Modelos_AutomaG.Precios", b =>
                {
                    b.Property<string>("idpre")
                        .HasColumnType("text")
                        .HasColumnName("idpre");

                    b.Property<decimal>("arancelpre")
                        .HasColumnType("numeric")
                        .HasColumnName("arancelpre");

                    b.Property<decimal>("inscripcionpre")
                        .HasColumnType("numeric")
                        .HasColumnName("inscripcionpre");

                    b.Property<decimal>("matriculapre")
                        .HasColumnType("numeric")
                        .HasColumnName("matriculapre");

                    b.Property<string>("monedapre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("monedapre");

                    b.Property<bool>("vigente")
                        .HasColumnType("boolean")
                        .HasColumnName("vigente");

                    b.HasKey("idpre");

                    b.ToTable("precios");
                });

            modelBuilder.Entity("Modelos_AutomaG.Programas", b =>
                {
                    b.Property<string>("idpro")
                        .HasColumnType("text")
                        .HasColumnName("idpro");

                    b.Property<string>("descripcionpro")
                        .HasColumnType("text")
                        .HasColumnName("descripcionpro");

                    b.Property<string>("duracionpro")
                        .HasColumnType("text")
                        .HasColumnName("duracionpro");

                    b.Property<string>("estadopro")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estadopro");

                    b.Property<string>("idcam")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("idcam");

                    b.Property<string>("idmod")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("idmod");

                    b.Property<string>("idniv")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("idniv");

                    b.Property<string>("idpre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("idpre");

                    b.Property<string>("nombrepro")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombrepro");

                    b.HasKey("idpro");

                    b.HasIndex("idcam");

                    b.HasIndex("idmod");

                    b.HasIndex("idniv");

                    b.HasIndex("idpre");

                    b.ToTable("programas");
                });

            modelBuilder.Entity("Modelos_AutomaG.ProgramasHorarios", b =>
                {
                    b.Property<string>("idpro")
                        .HasColumnType("text")
                        .HasColumnName("idpro");

                    b.Property<string>("idhor")
                        .HasColumnType("text")
                        .HasColumnName("idhor");

                    b.HasKey("idpro", "idhor");

                    b.HasIndex("idhor");

                    b.ToTable("programas_horarios", (string)null);
                });

            modelBuilder.Entity("Modelos_AutomaG.Roles", b =>
                {
                    b.Property<string>("idrol")
                        .HasColumnType("text")
                        .HasColumnName("idrol");

                    b.Property<string>("codigorol")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("codigorol");

                    b.Property<string>("nombrerol")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombrerol");

                    b.HasKey("idrol");

                    b.ToTable("roles");
                });

            modelBuilder.Entity("Modelos_AutomaG.TiposHorario", b =>
                {
                    b.Property<string>("idtipo")
                        .HasColumnType("text")
                        .HasColumnName("idtipo");

                    b.Property<string>("nombretipo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombretipo");

                    b.HasKey("idtipo");

                    b.ToTable("tipos_horario");
                });

            modelBuilder.Entity("Modelos_AutomaG.UsuarioRoles", b =>
                {
                    b.Property<string>("idusu")
                        .HasColumnType("text")
                        .HasColumnName("idusu");

                    b.Property<string>("idrol")
                        .HasColumnType("text")
                        .HasColumnName("idrol");

                    b.HasKey("idusu", "idrol");

                    b.HasIndex("idrol");

                    b.ToTable("usuario_roles", (string)null);
                });

            modelBuilder.Entity("Modelos_AutomaG.Usuarios", b =>
                {
                    b.Property<string>("idusu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("idusu");

                    b.Property<bool>("activousu")
                        .HasColumnType("boolean")
                        .HasColumnName("activousu");

                    b.Property<string>("emailusu")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("emailusu");

                    b.Property<DateTime>("fechacreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fechacreacion");

                    b.Property<string>("nombreusu")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombreusu");

                    b.Property<string>("passwordhash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("passwordhash");

                    b.HasKey("idusu");

                    b.ToTable("usuarios");
                });

            modelBuilder.Entity("Modelos_AutomaG.Aspirantes", b =>
                {
                    b.HasOne("Modelos_AutomaG.Contactos", "Contacto")
                        .WithMany("Aspirantes")
                        .HasForeignKey("idcon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contacto");
                });

            modelBuilder.Entity("Modelos_AutomaG.Horarios", b =>
                {
                    b.HasOne("Modelos_AutomaG.TiposHorario", "TipoHorario")
                        .WithMany("Horarios")
                        .HasForeignKey("idtipo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoHorario");
                });

            modelBuilder.Entity("Modelos_AutomaG.Programas", b =>
                {
                    b.HasOne("Modelos_AutomaG.CamposConocimiento", "Campo")
                        .WithMany("Programas")
                        .HasForeignKey("idcam")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Modelos_AutomaG.Modalidades", "Modalidad")
                        .WithMany("Programas")
                        .HasForeignKey("idmod")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Modelos_AutomaG.Niveles", "Nivel")
                        .WithMany("Programas")
                        .HasForeignKey("idniv")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Modelos_AutomaG.Precios", "Precio")
                        .WithMany("Programas")
                        .HasForeignKey("idpre")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campo");

                    b.Navigation("Modalidad");

                    b.Navigation("Nivel");

                    b.Navigation("Precio");
                });

            modelBuilder.Entity("Modelos_AutomaG.ProgramasHorarios", b =>
                {
                    b.HasOne("Modelos_AutomaG.Horarios", "Horario")
                        .WithMany("ProgramasHorarios")
                        .HasForeignKey("idhor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Modelos_AutomaG.Programas", "Programa")
                        .WithMany("ProgramasHorarios")
                        .HasForeignKey("idpro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Horario");

                    b.Navigation("Programa");
                });

            modelBuilder.Entity("Modelos_AutomaG.UsuarioRoles", b =>
                {
                    b.HasOne("Modelos_AutomaG.Roles", "Rol")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("idrol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Modelos_AutomaG.Usuarios", "Usuario")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("idusu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Modelos_AutomaG.CamposConocimiento", b =>
                {
                    b.Navigation("Programas");
                });

            modelBuilder.Entity("Modelos_AutomaG.Contactos", b =>
                {
                    b.Navigation("Aspirantes");
                });

            modelBuilder.Entity("Modelos_AutomaG.Horarios", b =>
                {
                    b.Navigation("ProgramasHorarios");
                });

            modelBuilder.Entity("Modelos_AutomaG.Modalidades", b =>
                {
                    b.Navigation("Programas");
                });

            modelBuilder.Entity("Modelos_AutomaG.Niveles", b =>
                {
                    b.Navigation("Programas");
                });

            modelBuilder.Entity("Modelos_AutomaG.Precios", b =>
                {
                    b.Navigation("Programas");
                });

            modelBuilder.Entity("Modelos_AutomaG.Programas", b =>
                {
                    b.Navigation("ProgramasHorarios");
                });

            modelBuilder.Entity("Modelos_AutomaG.Roles", b =>
                {
                    b.Navigation("UsuarioRoles");
                });

            modelBuilder.Entity("Modelos_AutomaG.TiposHorario", b =>
                {
                    b.Navigation("Horarios");
                });

            modelBuilder.Entity("Modelos_AutomaG.Usuarios", b =>
                {
                    b.Navigation("UsuarioRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
